### ISSUE TITLE
Gruvbox Light uses invalid background color

### ISSUE THREAD

**Issue by lunaror** [henices/logseq-flow-nord#24]
Gruvbox light theme uses invalid background color, but Dark variant is correct:

Gruvbox light:

<img width="1427" alt="image" src="https://github.com/henices/logseq-flow-nord/assets/121626993/631de688-7682-4aed-9871-51dcd4f11e72">

Gruvbox dark:

<img width="1422" alt="image" src="https://github.com/henices/logseq-flow-nord/assets/121626993/ef80656c-b81e-4cf7-9025-c97d193edc37">

CSS file was generated using `gen_custom_css.sh` script.

Note that `src/palettes/gruvbox.css` file contained typos and old variables names, so I had to modify it a bit:

```css
.dark-theme,
html[data-theme='dark'] {
    --background-color-h: 0;
    --background-color-s: 0%;
    --background-color-l: 16%;
    --cl-background: 0,0%,26%;
    --cl-text-color: 38, 41%, 71%;
    --cl-primary: 24, 76%, 61%;
    --cl-accent: 167, 23%, 59%;
    --cl-secondary: 70, 36%, 55%;
}

.white-theme,
html[data-theme='light'] {
    --background-color-h: 46;
    --background-color-s: 33%;
    --background-color-l: 84%;
    --cl-background: 46,33%,74%;
    --cl-text-color: 36,14%,22%;
    --cl-primary: 0,49%,52%;
    --cl-secondary: 191,28%,37%;
    --cl-accent: 70,45%,33%;
}
```

**Comment by henices** [comment]
Thanks for reporing this issue, but I can't reproduce it.

![image](https://github.com/henices/logseq-flow-nord/assets/929715/afb30afb-876f-4171-a8dc-7b8a07b89909)

Gruvbox is a custom color palette, the correct way to use it is:

1)  Select ...  -> theme -> Flow Nord Theme - custom
2)  Settings -> edit custom.css 

```css
.dark-theme,
html[data-theme='dark'] {
    --ct-bg-color-h: 0;
    --ct-bg-color-s: 0%;
    --ct-bg-color-l: 16%;
    --ct-bg-color: 0,0%,26%;
    --ct-text-color: 38, 41%, 71%;
    --ct-primariy-color: 24, 76%, 61%;
    --ct-accent-color: 167, 23%, 59%;
    --ct-secondary-color: 70, 36%, 55%;
}

.white-theme,
html[data-theme='light'] {
    --ct-bg-color-h: 46;
    --ct-bg-color-s: 33%;
    --ct-bg-color-l: 84%;
    --ct-bg-color: 46,33%,74%;
    --ct-text-color: 36,14%,22%;
    --ct-primariy-color: 0,49%,52%;
    --ct-secondary-color: 191,28%,37%;
    --ct-accent-color: 70,45%,33%;
}
```
